#!/usr/bin/env/python

import logging
import time

from psycopg2 import OperationalError

import environ
from reporting_bot import Config, ReportLoggingBot

if __name__ == '__main__':
    config = environ.to_config(Config)
    logger = logging.getLogger(__name__)

    while True:
        try:
            bot = ReportLoggingBot(config)
        except psycopg2.OperationalError as err:
            logger.warning('Could not connect to database')
            logger.warning(err)

            logger.warning('Retrying in 30 seconds')

            # Try again in 30 seconds
            time.sleep(30)
            continue

        # Split into separate try, to ensure database connection deconstruction
        try:
            bot.poll_events()
        finally:
            # Make sure the bot gets deconstructed and the database connection with it
            del bot
        time.sleep(300)
